### ISSUE TITLE
set() keep counting even there are key exist previously

### ISSUE THREAD

**Issue by SharifPoetra** [youKnowOwO/mongotrize#2]
I think this should be checked if the key exist so do not count it.
https://github.com/youKnowOwO/mongotrize/blob/895c6df7715654daeae8fceabdfb5b2835eb94dd/src/libs/MongoMap.ts#L33

**Comment by youKnowOwO** [comment]
I see '-')

**Comment by youKnowOwO** [comment]
b5e7d1b4bf230eb81e982ff34bd4ab298999faa3
